# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json

steps:
  - label: "Update git fetch refmap"
    plugins:
      - Hivebrite/git-flags#v0.0.1:
          fetch: "-v --prune --refmap='+refs/pull/{{BUILDKITE_PULL_REQUEST}}/merge:refs/pull/{{BUILDKITE_PULL_REQUEST}}/merge'"

  - label: "Example test"
    command: echo "Hello!"
